# Generated by Django 4.0.2 on 2022-10-16 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shablons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(verbose_name='Ссылка на картинку')),
                ('name', models.TextField(verbose_name='Название')),
                ('massa', models.TextField(default='142 MB', verbose_name='Вес файла с MB')),
                ('typical', models.TextField(verbose_name='Тип приложения(Например "Graphic editor")')),
                ('kolvo', models.IntegerField(default=5, verbose_name='Количество звезд(До 5)')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 10, 16, 19, 15, 1, 320323))),
            ],
        ),
    ]
