# Generated by Django 4.0.2 on 2022-10-16 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shablons',
            name='kolvo_download',
            field=models.IntegerField(default=1525, verbose_name='Количество людей, установивших приложение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shablons',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 19, 19, 47, 765484)),
        ),
    ]
