# Generated by Django 4.0.2 on 2022-10-16 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shablons_kolvo_download_alter_shablons_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shablons',
            name='kolvo',
        ),
        migrations.AlterField(
            model_name='shablons',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 19, 23, 48, 473348)),
        ),
    ]
