# Generated by Django 4.0.6 on 2022-11-24 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_shablons_kolvo_alter_shablons_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shablons',
            name='linkToDownload',
            field=models.TextField(default='', verbose_name='Ссылка на скачивание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shablons',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 18, 53, 33, 830550)),
        ),
    ]
