# Generated by Django 4.0.6 on 2022-11-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='owner',
            new_name='user',
        ),
    ]
