# Generated by Django 4.0.2 on 2022-11-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='user_rights',
            field=models.CharField(choices=[('no_rights', 'no_rights'), ('standart_user', 'standart_user'), ('administrator', 'administrator')], default='standart_user', max_length=30),
        ),
    ]
