# Generated by Django 4.0.6 on 2022-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_owner_domain_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='name_domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='name',
            field=models.TextField(default='2022-12-1', verbose_name='Name of domain (search function)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='type',
            field=models.TextField(choices=[('LOCO', 'LOCO')]),
        ),
    ]
