# Generated by Django 4.0.2 on 2022-12-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_groups_alter_user_user_permissions'),
        ('main', '0002_rename_owner_domain_user'),
    ]

    operations = [
    ]
