# Generated by Django 4.0.2 on 2022-11-23 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_custom_user_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_domain', models.TextField(verbose_name='Name of domain(search function)')),
                ('variant', models.CharField(choices=[('steamfish', 'steamfish')], max_length=30, verbose_name='Choice of shablons')),
                ('downloads', models.IntegerField(default=0, verbose_name='number of downloaded programs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
