# Generated by Django 4.0.2 on 2022-12-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20221204_1722'),
        ('main', '0003_remove_domain_name_domain_domain_name_and_more'),
    ]

    operations = [
    ]
