# Generated by Django 4.0.2 on 2022-11-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='loco',
            field=models.BooleanField(default=False, verbose_name='Loco acces?'),
        ),
    ]
