# Generated by Django 4.0.2 on 2022-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absuser',
            name='load_to',
            field=models.IntegerField(default=0, verbose_name='Сколько загрузили'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absuser',
            name='tarif',
            field=models.CharField(choices=[('6gb', '6gb'), ('10gb', '10gb'), ('2gb', '2gb'), ('4gb', '4gb'), ('unlim', 'unlim')], max_length=50, verbose_name='Тариф пользователя'),
        ),
    ]
